# Travis build file for alphaTab

# Well, our language is Haxe but as I we use Ant for building
# we choose Java. 
language: java
  
before_install:
  # Install Haxe before build
  - sudo apt-get update                               
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  # Install NPM Packages 
  - npm install uglify-js -g
  # Work on head
  - git checkout master

# Actual build
script:
  - ant all
  
# Push back rebuilt sources to repository
env:
  global:
  secure: "Y56WPxLukArc3hrFCQ0s6E/SNHipt/e+6NoA5Vey3a1Gf1wOx6KoV7Vk1hcxs+8B3M8kuAJudocf/QdeZ2jFS68ImIJLWxbW81G8l6aoUZwHdUsYN4izbRkcXSp5TTqRE7dkIUdgwAm0uAt7dCOAOi0LTbjv6muN4zftBxP3LMg="
  
after_success: 
  - git config --global user.name "travis-ci" 
  - git config --global user.email "travis@travis-ci.org" 
  - git status 
  - git add -A 
  - git commit -m "Travis autobuild $TRAVIS_BUILD_NUMBER"
  - git push -q https://${GH_TOKEN}@github.com/CoderLine/alphaTab master