# Travis build file for alphaTab

# Well, our language is Haxe but as I we use Ant for building
# we choose Java. 
language: java

# Install Haxe before build
before_install:
  - sudo apt-get update                               
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib

# Actual build
script:
  - ant js      # JavaScript Build
  - ant cs      # C# Build