# Travis build file for alphaTab

# TODO: Create a setup for compiling with Mono and Saltarelle
language: java
  
before_install:

# Actual build
script:  
  
# Push back rebuilt sources to repository
env:
  global:
    secure: "Y56WPxLukArc3hrFCQ0s6E/SNHipt/e+6NoA5Vey3a1Gf1wOx6KoV7Vk1hcxs+8B3M8kuAJudocf/QdeZ2jFS68ImIJLWxbW81G8l6aoUZwHdUsYN4izbRkcXSp5TTqRE7dkIUdgwAm0uAt7dCOAOi0LTbjv6muN4zftBxP3LMg="
  
after_success: 
  - git config --global user.name "travis-ci" 
  - git config --global user.email "travis@travis-ci.org" 
  - git status 
  - git add -A 
  - git commit -m "Travis autobuild $TRAVIS_BUILD_NUMBER"
  - git push -q https://${GH_TOKEN}@github.com/CoderLine/alphaTab master