# Travis build file for alphaTab

# Well, our language is Haxe but as I we use Ant for building
# we choose Java. 
language: java
  
before_install:
  # Install Haxe before build
  - sudo apt-get update                               
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  # Install NPM Packages 
  - npm install uglify-js -g

# Actual build
script:
  - ant all