version: 0.9.1.{build}
# branches to build
branches:
  only:
    - develop
    
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  nodejs_version: '8'
  global:
    HAXELIB_ROOT: C:\projects\haxelib
  access_token:
    secure: ig+MHQrCziKIZzGkDBsOTuusdSATGEXh79QCG8b4guSHAcM0+uYy0zGoVTKG446Q
skip_commits:
  author: AlphaTab Build Agent

install:
  #
  # Haxe installation
  - ps: Set-Service wuauserv -StartupType Manual
  # Install the neko chocolatey package (https://chocolatey.org/packages/neko)
  - cinst neko --version 2.2.0 -y
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe --version 3.4.4 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install project dependencies
  # `> log.txt || type log.txt` is for muting the output unless there is an error
  - haxelib install munit  > log.txt || type log.txt && cmd /C exit 1
  - haxelib install hamcrest  > log.txt || type log.txt && cmd /C exit 1
  - haxelib list
  #
  # Npm/Uglifyjs installation
  - npm install -g uglify-js
  - RefreshEnv

dotnet_csproj:
  patch: true
  file: 'Directory.Build.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

build:
  parallel: true
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal

before_build:
- nuget restore
- dotnet restore
  
test:
  assemblies:
    only: 
      - Source\AlphaTab.Test.CSharp\bin\Release\net471\AlphaTab.Test.CSharp.dll
  
artifacts:
  # JavaScript Output
  - path: JavaScript\*.*
    name: JavaScript
  # NuGet package output 
  - path: Source\AlphaTab.CSharp\Bin\$(configuration)\*.nupkg
    name: NuGet

deploy:
  # My Get (Every Build)
  - provider: NuGet
    server: https://www.myget.org/F/coderline/api/v3/index.json
    api_key:
      secure: sQI+q8oHDFwWAWOy/pvP4zHehqNASufniwX7aOpN03YlcKt44ZX/55guh2kGoJ2n
    artifact: NuGet  
  # NuGet.org (Only Tagged on Master)
  - provider: NuGet
    api_key:
      secure: 89W5Zsv2maiKx7/Bmn5zFFlKjPC2J7NnDRhPrpeH9hEnVvtDlWt04xR+kYi52dPt
    artifact: NuGet
    on:
      branch: master
      appveyor_repo_tag: true
      
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "appveyor@alphatab.net"
  - git config --global user.name "AlphaTab Build Agent"
  - git add Directory.Build.props
  - git commit -m '$(env:APPVEYOR_REPO_COMMIT_MESSAGE) (build: $(env:APPVEYOR_BUILD_VERSION))' 
  - git push origin $(env:APPVEYOR_REPO_BRANCH)
