version: 0.9.1.{build}
image: Visual Studio 2017
configuration:
- Release
platform:
- Any CPU

before_build:
- dotnet restore
dotnet_csproj:
  patch: true
  file: 'Directory.Build.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

artifacts:
- path: JavaScript\*.*
  name: JavaScript
- path: Source\AlphaTab.CSharp\Bin\Release\*.nupkg
  name: NuGet

test:
  assemblies:
    only: 
      - Source\AlphaTab.Test.CSharp\bin\Release\net471\AlphaTab.Test.CSharp.dll
# branch specific configurations
-
  branches:
    only:
      - develop    
  deploy:
  - provider: NuGet
    server: https://www.myget.org/F/coderline/api/v3/index.json
    api_key:
      secure: sQI+q8oHDFwWAWOy/pvP4zHehqNASufniwX7aOpN03YlcKt44ZX/55guh2kGoJ2n
    artifact: NuGet